server:
  port: 8082
# Mysql?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carbroom?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  security:
    user:
      name: user
      password: 111111
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mybatis-plus:
    mapper-localions: classpath:/mapper/*.xml
zh:
  jwt:
    header: Authorization
    expire: 604800
    secret: zhao156985yong1754qi2587jsfgkja5



